In [1]:
import pandas as pd

train = pd.read_pickle("../data/processed/train.pkl")
validation = pd.read_pickle("../data/processed/validation.pkl")
test = pd.read_pickle("../data/processed/test.pkl")

In [2]:
train.shape, validation.shape, test.shape

((473436, 15), (118664, 15), (121160, 15))

In [3]:
validation["naive_prediction"] = validation["lag_1"]

In [4]:
validation[["StockCode", "Date", "Demand", "lag_1", "naive_prediction", "target"]].head(
    15
)

     StockCode       Date  Demand  lag_1  naive_prediction  target
1036     10125 2011-08-20       0   20.0              20.0     0.0
1037     10125 2011-08-21       0    0.0               0.0     0.0
1038     10125 2011-08-22       0    0.0               0.0     0.0
1039     10125 2011-08-23       0    0.0               0.0    25.0
1040     10125 2011-08-24      25    0.0               0.0     0.0
1041     10125 2011-08-25       0   25.0              25.0     0.0
1042     10125 2011-08-26       0    0.0               0.0     0.0
1043     10125 2011-08-27       0    0.0               0.0     0.0
1044     10125 2011-08-28       0    0.0               0.0     0.0
1045     10125 2011-08-29       0    0.0               0.0     0.0
1046     10125 2011-08-30       0    0.0               0.0     0.0
1047     10125 2011-08-31       0    0.0               0.0     0.0
1048     10125 2011-09-01       0    0.0               0.0     0.0
1049     10125 2011-09-02       0    0.0               0.0     0.0
1050     10125 2011-09-03       0    0.0               0.0     0.0

In [6]:
from sklearn.metrics import mean_absolute_error

mae_naive = mean_absolute_error(validation["target"], validation["naive_prediction"])

mae_naive

11.302534888424459

In [7]:
from sklearn.metrics import mean_squared_error

rmse_naive = (
    mean_squared_error(validation["target"], validation["naive_prediction"]) ** 0.5
)

rmse_naive

49.119678713502225

In [8]:
zero_actual = validation["target"] == 0

zero_prediction_correct = (validation.loc[zero_actual, "naive_prediction"] == 0).mean()

zero_prediction_correct

np.float64(0.7388078031879823)

In [10]:
baseline_data = (
    pd.concat([train, validation, test], ignore_index=True)
    .sort_values(["StockCode", "Date"])
    .copy()
)

In [11]:
baseline_data["ma_7"] = baseline_data.groupby("StockCode")["Demand"].transform(
    lambda x: x.rolling(7).mean()
)

In [12]:
baseline_data[["StockCode", "Date", "Demand", "ma_7"]].head(15)

   StockCode       Date  Demand       ma_7
0      10002 2010-12-29       0        NaN
1      10002 2010-12-30       0        NaN
2      10002 2010-12-31       0        NaN
3      10002 2011-01-01       0        NaN
4      10002 2011-01-02       0        NaN
5      10002 2011-01-03       0        NaN
6      10002 2011-01-04       0   0.000000
7      10002 2011-01-05      12   1.714286
8      10002 2011-01-06      60  10.285714
9      10002 2011-01-07       1  10.428571
10     10002 2011-01-08       0  10.428571
11     10002 2011-01-09       0  10.428571
12     10002 2011-01-10       0  10.428571
13     10002 2011-01-11      24  13.857143
14     10002 2011-01-12       0  12.142857